import { ClerkProvider, SignInButton, SignUpButton, Show, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/smooth-scroll";
import { Suspense } from "react";
import { ClientOnly } from "@/components/client-only";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <Suspense>
            <SmoothScroll>
              <header className="flex justify-between items-center p-4 border-b">
                <div>
                  <h1 className="text-xl font-bold">My App</h1>
                </div>
                <div className="flex gap-4">
                  <ClientOnly>
                    <Show when="signed-out">
                      <SignInButton />
                      <SignUpButton />
                    </Show>
                    <Show when="signed-in">
                      <UserButton />
                    </Show>
                  </ClientOnly>
                </div>
              </header>
              {children}
            </SmoothScroll>
          </Suspense>
        </ClerkProvider>
      </body>
    </html>
  );
}
